name: quran_ai_reader
description: "Application Flutter Coran Intelligent avec reconnaissance vocale et lecture assistée"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1

  # State Management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

  # Speech & Audio
  speech_to_text: ^7.0.0
  flutter_tts: ^4.1.0
  just_audio: ^0.9.39
  audioplayers: ^6.1.0
  permission_handler: ^11.3.1

  # Text Processing & Matching
  string_similarity: ^2.0.0

  # Database & Storage
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

  # Network & HTTP
  http: ^1.2.2
  dio: ^5.7.0

  # JSON & Data Processing
  json_annotation: ^4.9.0

  # UI Components
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.2

  # Platform Integration
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  geolocator: ^13.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/quran/
    - assets/fonts/
    - assets/images/
    - assets/audio/

  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
