name: quran_ai_reader
description: Application Coran Intelligente avec Maps et reconnaissance vocale
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Design
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  
  # Navigation & State Management
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  
  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_places_flutter: ^2.0.6
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  permission_handler: ^11.2.0
  
  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0
  
  # Database & Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  
  # Audio & Speech
  just_audio: ^0.9.36
  audio_session: ^0.1.18
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.3
  
  # Firebase (optionnel)
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  cloud_firestore: ^4.13.6
  
  # Utilities
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  flutter_compass: ^0.8.0
  sensors_plus: ^4.0.2
  
  # JSON Serialization
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # Icons & Images
  flutter_svg: ^2.0.9
  photo_view: ^0.14.0
  
  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/fonts/
    - assets/quran/
    - assets/audio/
  
  fonts:
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700