name: quran_ai_reader
description: "Application Flutter Coran Intelligent avec reconnaissance vocale, lecture assistée et localisation de mosquées"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  go_router: ^14.2.7
  flutter_screenutil: ^5.9.3
  responsive_framework: ^1.5.1
  google_fonts: ^6.1.0
  flutter_animate: ^4.3.0
  cached_network_image: ^3.3.1

  # State Management
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.3

  # Speech & Audio
  speech_to_text: ^7.0.0
  flutter_tts: ^4.1.0
  just_audio: ^0.9.39
  audioplayers: ^6.1.0
  audio_session: ^0.1.18

  # Maps & Location
  google_maps_flutter: ^2.5.3
  geolocator: ^13.0.1
  geocoding: ^2.1.1
  google_places_flutter: ^2.0.6
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  permission_handler: ^11.3.1

  # Text Processing & Matching
  string_similarity: ^2.0.0

  # Database & Storage
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Network & HTTP
  http: ^1.2.2
  dio: ^5.7.0

  # JSON & Data Processing
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

  # UI Components
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.2
  flutter_svg: ^2.0.9
  photo_view: ^0.14.0

  # Platform Integration
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  url_launcher: ^6.2.2
  share_plus: ^7.2.1
  connectivity_plus: ^5.0.2
  intl: ^0.19.0
  flutter_compass: ^0.8.0
  sensors_plus: ^4.0.2

  # Firebase (optionnel)
  firebase_core: ^2.24.2
  firebase_analytics: ^10.7.4
  cloud_firestore: ^4.13.6

  # Notifications
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/quran/
    - assets/fonts/
    - assets/images/
    - assets/audio/

  fonts:
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
    - family: Amiri
      fonts:
        - asset: assets/fonts/Amiri-Regular.ttf
          weight: 400
        - asset: assets/fonts/Amiri-Bold.ttf
          weight: 700
