name: Android Release APK

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_ALIAS_PASSWORD: ${{ secrets.ANDROID_KEY_ALIAS_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter version
        run: flutter --version

      - name: Decode Android Keystore
        if: ${{ env.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          mkdir -p android/app
          echo "${ANDROID_KEYSTORE_BASE64}" | base64 -d > android/app/upload-keystore.jks

      - name: Create key.properties
        if: ${{ env.ANDROID_KEYSTORE_PASSWORD != '' && env.ANDROID_KEY_ALIAS != '' && env.ANDROID_KEY_ALIAS_PASSWORD != '' }}
        run: |
          cat > android/key.properties <<EOF
          storeFile=android/app/upload-keystore.jks
          storePassword=${ANDROID_KEYSTORE_PASSWORD}
          keyAlias=${ANDROID_KEY_ALIAS}
          keyPassword=${ANDROID_KEY_ALIAS_PASSWORD}
          EOF

      - name: Flutter pub get
        run: flutter pub get

      - name: Generate code (build_runner)
        run: |
          flutter packages pub run build_runner build --delete-conflicting-outputs || true

      - name: Build APK (release)
        run: flutter build apk --release

      - name: Build App Bundle (release)
        run: flutter build appbundle --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: |
            build/app/outputs/flutter-apk/*.apk
            android/app/build/outputs/apk/release/*.apk

      - name: Upload App Bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: |
            build/app/outputs/bundle/release/*.aab
            android/app/build/outputs/bundle/release/*.aab

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/app/outputs/flutter-apk/*.apk
            android/app/build/outputs/apk/release/*.apk
            build/app/outputs/bundle/release/*.aab
            android/app/build/outputs/bundle/release/*.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}